name: Compile and Run C Code

on:
  push:
    branches:
      - main  # This will trigger the workflow when you push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # This uses a Linux environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This checks out the repository code

      - name: Install GCC
        run: sudo apt-get install gcc  # Install GCC (the C compiler)

      - name: Compile C Code
        run: gcc -o output restmanagement.c  # Compile the C code (replace 'your-c-code.c' with your filename)

      - name: Run C Code
        run: ./output  # Run the compiled C code
