name: Run C Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get install build-essential

      - name: Compile C Code
        run: gcc your-c-code.c -o output

      - name: Run the C Code
        run: ./output
